<?php 
    $formatting = $this->getHelper('DataFormatting');    
?>
<div class="headerPop">
    <div class="fl ml12 mt5"><?php echo ($this->club?$this->translate('edit').' '.$this->club['name']:$this->translate(array('add','Website'))); ?></div>
        <a class="closebtnPop" onclick="$('.pop').hide(); Button.enableAdd(); return false" title="<?php echo $this->translate('close');?>"></a>
</div>
<div class="contentPop">
    <form action="users/save" method="POST" id="ajaxForm" onsubmit="Form.submit('ajaxForm');return false;" class="ml20">
        <input type="hidden" class="textInput w190" name="id" value="<?php echo ($this->club?$this->club['id']:''); ?>"/>
        <table class="table_edit">
            <tbody>
                <tr>
                    <td>
                        <label class="pl18" for="clubeName" style=""><?php echo $this->translate(array('in','website')).' '.$formatting->markAsRequired(); ?> </label>
                    </td>
                    <td>
                        <select name="websiteId">
							<?php
								foreach($this->websites as $key=>$value){
							?>
								<option value="<?php echo $value['id']; ?>" <?php echo (isset($this->club['website_id']) && $value['id'] == $this->club['website_id']) ?>><?php echo $value['name']; ?></option>
							<?php 
								}
							?>
						</select>
						
                    </td>
                    
                </tr>
				<tr>
                    <td>
                        <label class="pl18" for="clubeName" style=""><?php echo $this->translate(array('name')).' '.$formatting->markAsRequired(); ?> </label>
                    </td>
                    <td>
                        <input type="text" class="textInput w190" name="name" value="<?php echo ($this->club?$this->club['url']:''); ?>"/>
                    </td>
                    
                </tr>
               
            </tbody>
        </table>
        <input type="button" class="green mr12 mt8 mb14 mt20" onclick="Form.submit('ajaxForm');" value="<?php echo $this->translate('save');?>" title="<?php echo $this->translate(array('save', 'club'));?>">
    </form>    
</div>