<script type="text/javascript">
    Grid.init('users/list');
	$("#ajaxFilter").jqTransform();
</script>
<div class="scroll">
    <table class="zebra">
        <colgroup>
            <col class="w48">
            <col class="w120">
            <col class="w75">
            <col class="">
        </colgroup>
        <tbody>
        <?php 
        $key = 0;        
        foreach ($this->items as $item){
        ?>
        <tr>   
            <td class="middle left pl13" title="">
                <input type="checkbox" name="chekbox" id="<?php echo ($id = $this->htmlEscape($item['id']));?>" onclick="removeForm.chekboxChange(this)"/>
            </td>     
            <td class="middle right pl13"> 
                <a href="description" class="ico_edit_polygon mr12" title="<?php echo $this->translate(array('edit','details','of')).' '.$this->htmlEscape($item['name']); ?>"></a>
            </td>
            <td class="middle left pl0 center" title="<?php echo ($val = $this->htmlEscape($item['id']));?>"><a href="descriptions/index/userId/<?php echo $id ?>"  target="_blank" class="mr12 noAjax" title="<?php echo $this->translate(array('edit','details','of')).' '.$this->htmlEscape($item['name']); ?>"><?php echo $val;?></a></td>
			<td class="middle left pl0 center" title="<?php echo ($val = $this->htmlEscape($item['name']));?>"> <a href="descriptions/index/userId/<?php echo $id ?>" target="_blank" class="mr12 noAjax" title="<?php echo $this->translate(array('edit','details','of')).' '.$this->htmlEscape($item['name']); ?>"><?php echo $val;?></a></td>
            <!--<td class="middle left header br0" title="<?php echo ($val = $this->htmlEscape($item['name']));?>">
                <a href="description"  class="link"><?php //echo $item['avgStars'];?></a>
            </td>-->
        </tr>
        <?php
            $key++;
        } 
        if($key == 0){?>
            <tr>
                <td colspan="13" class="center middle"><?php echo $this->translate('no.record.available');?></td>
            </tr>
        <?php }?>
       </tbody>
   </table>
</div>   
<?php $this->paginator($this->filter, $this->itemCount) ?>