ALTER TABLE `teeflow`.`messages` ADD COLUMN `message_marshal` TEXT NULL AFTER `active`; 
UPDATE `teeflow`.`messages` SET `message_marshal`='battery low 1 ()' WHERE `id`='9'; 
UPDATE `teeflow`.`messages` SET `message_marshal`='battery low 2 ()' WHERE `id`='10'; 
UPDATE `teeflow`.`messages` SET `message_marshal`='Coused by other players heavy interference' WHERE `id`='12'; 
UPDATE `teeflow`.`messages` SET `message_marshal`='player in front of you make light interference' WHERE `id`='7'; 
UPDATE `teeflow`.`messages` SET `message_marshal`='player in front of you make light interference' WHERE `id`='8'; 
UPDATE `teeflow`.`messages` SET `message_marshal`='please play faster' WHERE `id`='1'; 
UPDATE `teeflow`.`messages` SET `message_marshal`='please start to play' WHERE `id`='5'; 
UPDATE `teeflow`.`messages` SET `message_marshal`='coused heavy interference to players behind' WHERE `id`='6'; 
UPDATE `teeflow`.`messages` SET `message_marshal`='You are in control sector' WHERE `id`='15'; 
UPDATE `teeflow`.`messages` SET `message_marshal`='In overtaking situtation' WHERE `id`='11'; 
UPDATE `teeflow`.`messages` SET `message_marshal`='In Pause sector' WHERE `id`='14'; 
UPDATE `teeflow`.`messages` SET `message_marshal`='You are in pause sector' WHERE `id`='16'; 
UPDATE `teeflow`.`messages` SET `message_marshal`='You are in problem sector' WHERE `id`='13'; 
UPDATE `teeflow`.`messages` SET `message_marshal`='You are in start free sector' WHERE `id`='17'; 
UPDATE `teeflow`.`messages` SET `message_marshal`='you are out of geo fence' WHERE `id`='2'; 
UPDATE `teeflow`.`messages` SET `message_marshal`='you are playing in false order' WHERE `id`='3'; 
UPDATE `teeflow`.`messages` SET `message_marshal`='Playing very fast' WHERE `id`='4'; 
INSERT INTO `teeflow`.`messages`(`id`,`type`,`message`,`active`,`message_marshal`) VALUES ( NULL,'help_button',NULL,'0','Pressed help button'); 