<!DOCTYPE html>
<html>
<head>
    <?php 
        $jsHelper = $this->getHelper('js');
        $jsHelper->urlChecker();
        echo $this->headMeta();        
    ?>
    <title><?php echo $this->translate('project.name')?></title>
    <base href="<?php echo $this->baseUrl(); ?>" />
    <link rel="stylesheet" type="text/css" href="css/style.css" />   
    <link rel="stylesheet" type="text/css" href="css/jqtransform.css" />
    <link href="images/favico.png" rel="shortcut icon" type="image/x-icon"/>    
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTL9gOJWA7Yg_sD4F0XpfGfnL1LupMMW0&sensor=false"> </script>
    <?php
    echo $this->headScript()
    ->appendFile('js/jquery-1.8.2.min.js', 'text/javascript')
    ->appendFile('js/jquery-ui-1.10.3.custom.min.js', 'text/javascript')    
    ->appendFile('js/plugins/jquery.tablesorter.js', 'text/javascript')
    ->appendFile('js/plugins/jquery.form.js', 'text/javascript')
    ->appendFile('js/plugins/jquery.pnotify.min.js', 'text/javascript')
    ->appendFile('js/plugins/history.js', 'text/javascript')
    ->appendFile('js/plugins/jquery.maphilight.min.js', 'text/javascript')
    ->appendFile('js/plugins/jquery.mousewheel.js', 'text/javascript')    
    ->appendFile('js/plugins/jquery.jqtransform.js', 'text/javascript');        
    ?>
    <?php echo $this->action("index", "Jsmin"); ?>
    </head>
<body>
    <div id="header">
        <div class="inner-container">
        </div>
    </div>
    <div class="page_wrapper" id="container">
        <div id="nav">
            <ul id="nav_menu">
                
                <li class="">
                    <a href="website"><?php echo $this->translate('Websites');?></a>
                </li> 
               
                <li class="turnaments">
                    <a href="turnament"><?php echo $this->translate('Turnaments');?></a>
                </li> 
               
                <li class="users">
                    <a href="users"><?php echo $this->translate('Users');?></a>
                </li>
               
                <li class="descriptions">
                    <a href="descriptions"><?php echo $this->translate('Descriptions');?></a>
                </li> 			
            </ul>

        </div>    
         <div class="content_wrapper">
            <div class="content_container">
                <div class="panel">
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
            <!--<div class="cl"></div> -->
        </div>
    </div> 
</body>
</html>
